image: python:3.11-buster

stages:
  - test
  - deploy

services:
  - postgres:15
variables:
  TZ: "Asia/Tokyo"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: demo
  POSTGRES_PORT: 5432
  POSTGRES_SERVER: db

before_script:
  - echo "Preparing environment"
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --no-root

test:
  stage: test
  script:
    - echo "Running tests"
    - poetry run pytest

deploy:
  stage: deploy
  script:
    - echo "Deploy"
    - set -Ceux
    - mkdir -p -m 700 ~/.ssh
    - set +x
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - set -x
    - cat << EOS > ~/.ssh/config
      Host *
          StrictHostKeyChecking no
      EOS
    - cat <<EOS | ssh kishikawa@192.168.11.17 bash
      set -Ceux
      cd /home/kishikawa/gitlab/kishikawa/fastapi/
      git reset --hard
      git fetch origin
      git checkout "$CI_COMMIT_SHORT_SHA"
      docker-compose stop
      docker-compose up -d
      EOS
  only:
    - main