version: '3'
services:
  demo-app:
    build: .
    depends_on:
      - db
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: /src/entrypoint.sh
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_PORT: ${POSTGRES_PORT?Variable not set}
      WATCHFILES_FORCE_POLLING: true

  db:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
